apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../base
  - doppler-secret.yaml
  - issuer.yaml
  - certificate.yaml
  - ingress.yaml

images:
  - name: 30s-api
    newName: ghcr.io/30s-sh/30s-api
    newTag: v0.5.0

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api
      spec:
        replicas: 2
