# Copy to secrets.yaml and fill in values for local testing
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  THIRTY_SECS_ENV: "development"
  THIRTY_SECS_DATABASE_URL: "postgres://postgres:postgres@host.docker.internal:5432/thirty_secs"
  THIRTY_SECS_REDIS_URL: "redis://host.docker.internal:6379"
  THIRTY_SECS_UNKEY_ROOT_KEY: "unkey_xxx"
  THIRTY_SECS_UNKEY_API_ID: "api_xxx"
